'use strict'

const fs = require('fs')
const path = require('path')

const MARKER_START = '<!-- nutshell-harness:start -->'
const MARKER_END = '<!-- nutshell-harness:end -->'

// Append (or update) a Nutshell harness block in the workspace's CLAUDE.md,
// telling any LLM working in the project how to keep the G2 mirror in sync
// with the source docs.
function ensureClaudeMdHarness(workspaceRoot, { sourceDir, outputDir }) {
	const filePath = path.join(workspaceRoot, 'CLAUDE.md')
	const block = renderBlock({ sourceDir, outputDir })

	let existing = ''
	if (fs.existsSync(filePath)) existing = fs.readFileSync(filePath, 'utf8')

	const startIdx = existing.indexOf(MARKER_START)
	const endIdx = existing.indexOf(MARKER_END)

	let next
	if (startIdx !== -1 && endIdx !== -1 && endIdx > startIdx) {
		next = existing.slice(0, startIdx) + block + existing.slice(endIdx + MARKER_END.length)
	} else {
		next = existing
		if (next.length > 0 && !next.endsWith('\n')) next += '\n'
		if (next.length > 0) next += '\n'
		next += block
	}

	fs.writeFileSync(filePath, next, 'utf8')
}

function renderBlock({ sourceDir, outputDir }) {
	return [
		MARKER_START,
		'## Nutshell G2 docs mirror',
		'',
		`\`${outputDir}/\` is an auto-generated mirror of \`${sourceDir}/\`, reformatted for`,
		'Even Realities G2 glasses. It is gitignored. The user can change this path in',
		'VS Code settings under `nutshell.outputDocsPath` (common alternatives include',
		'`.nutshell-docs` for a hidden folder).',
		'',
		`**Do not edit files in \`${outputDir}/\` directly** — they are regenerated by the`,
		'Nutshell VS Code extension via Claude Code using the format rules in',
		'`nutshell-server`\'s `prompts/reformat-note.txt`.',
		'',
		`When you edit a file in \`${sourceDir}/\`, either:`,
		'',
		'1. Run **Nutshell: Transform Docs for G2** from the command palette to rebuild the mirror, or',
		'2. Enable `nutshell.autoTransformOnSave` in VS Code settings so the mirror stays current automatically.',
		'',
		MARKER_END,
		'',
	].join('\n')
}

module.exports = { ensureClaudeMdHarness }
